"""Hand-written 999-call and radio fragments.

Two jobs: they seed/pad the training set via POST /generate/ner/label-existing
(synchronous, so no waiting on a job), and they are the held-out set the
frontier-LLM comparison is scored on. Written by hand precisely so they are
NOT drawn from the same distribution as Pioneer's synthetic generation —
an eval set generated by the same process as the training set would flatter
the model and the judges would be right to say so.

Deliberately covers what a regex net cannot do: relative locations ("the room
above the garage"), self-corrections mid-call, spelled-out numbers, partial
fragments, and fire-service radio idiom.
"""

from __future__ import annotations

# Realistic panicked-caller speech; transcriber-style lowercase, no punctuation
# where a caller would not pause.
CALL_FRAGMENTS: list[str] = [
    "there's a fire at 14 mansfield road my mum's still inside",
    "we're at flat 3 62 whitworth street the kitchen's alight",
    "sorry it's not 22 it's 24 beckett avenue i got confused",
    "my dad's in the room above the garage he can't get down the stairs",
    "the whole back of the house is smoke my sister's in the loft",
    "number seven fairfield close the tumble dryer's caught fire",
    "she's upstairs in the front bedroom she uses oxygen there's a cylinder up there",
    "we got out through the patio doors but the baby's still in the nursery",
    "it started in the chip pan now the whole kitchen's gone",
    "i'm at 118 st leonards road the fire's next door but our loft's connected",
    "the front door's deadlocked we can't get back in",
    "there's gas bottles in the shed right against the back wall",
    "he's trapped in the bathroom the landing's full of smoke",
    "my nan's downstairs in the back room she's bedbound",
    "89 alderney gardens se15 the flat above ours is burning",
    "the stairs are gone we're in the top floor bedroom at the front",
    "i think there's someone in the basement flat we can't get down there",
    "the boiler cupboard's on fire it's in the hallway",
    "we're on the corner of hillcrest and ellerby the one with the blue door",
    "smoke's coming out the roof my neighbour's still in there she's 90",
    "fire's in the conservatory at the back the side gate's padlocked",
    "please hurry the kids are in the back bedroom upstairs",
    "there's paint thinners and white spirit in the garage",
    "it's a maisonette 41a coleridge way the rear escape is blocked with bins",
    "the electrics went bang in the utility room now it's flames",
]

# Terse fire-service radio idiom, source: "radio".
RADIO_FRAGMENTS: list[str] = [
    "persons reported two adults one child first floor rear",
    "flashover in the kitchen rear exit blocked",
    "making up front door compromised entering via rear",
    "casualty located ground floor lounge removing now",
    "gas cylinder confirmed in the kitchen evacuate to 50 metres",
    "fire spread to roof void from the first floor bedroom",
    "rear access via alleyway is clear appliance to remain on the road",
    "stairs untenable second casualty still first floor front",
    "hydrant located 40 metres north outside number 12",
    "smoke logging throughout ground floor origin appears to be the kitchen",
]

# Partial fragments as the realtime transcriber emits them: an entity forming
# across successive partials. The dedupe must fire once, then update.
PARTIAL_SEQUENCES: list[list[str]] = [
    ["we're at 23 lark", "we're at 23 larkfield", "we're at 23 larkfield road",
     "we're at 23 larkfield road london se15 4nd"],
    ["my mum's up", "my mum's upstairs", "my mum's upstairs in the back bed",
     "my mum's upstairs in the back bedroom"],
    ["the fire started", "the fire started in the kit",
     "the fire started in the kitchen"],
]


def all_texts() -> list[str]:
    """Everything, flattened — the input to label-existing."""
    return CALL_FRAGMENTS + RADIO_FRAGMENTS + [
        seq[-1] for seq in PARTIAL_SEQUENCES
    ]
